#%RAML 1.0 DataType
properties:
        tenantID:
          type: string
          required: true
          example: "101"
        username:
          type: string
          required: false
          example: "babu"